export const CREATE_USER = "CREATE_USER";
export const CREATED_USER = "CREATED_USER";
export const GET_USER = 'GET_USER';
export const GOTTEN_USER = 'GOTTEN_USER';
export const LOGIN_FORM = 'LOGIN_FORM';
export const SIGNUP_FORM = 'SIGNUP_FORM';
export const WRONG_INFO = 'WRONG_INFO';
export const UNDOWRONG_INFO = 'UNDOWRONG_INFO';
export const SEND_RECOVER = 'SEND_RECOVER';
export const UNDO_SIGNUP_ERROR = 'UNDO_SIGNUP_ERROR';
export const UNDO_UPDATE_USER_ERROR = 'UNDO_UPDATE_USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATED_USER = 'UPDATED_USER';

export const WRONG_UPDATE_USER = 'WRONG_UPDATE_USER';


export const RESET_UPDATE_MESSAGE = 'RESET_UPDATE_MESSAGE';



// Main Room Messages
export const GET_MAIN_ROOM_MESSAGES = "GET_MAIN_ROOM_MESSAGES";
export const SET_MAIN_ROOM_MESSAGE = "SET_MAIN_ROOM_MESSAGE";
export const ERROR_FETCHING_MAIN_MESSAGES = "ERROR_FETCHING_MAIN_MESSAGES";
export const POST_MESSAGE = "POST_MESSAGE";
export const POSTED_MESSAGE = "POSTED_MESSAGE";


// Versus Mode Main Room Messages
export const GET_VERSUS_LOBBY_MESSAGES = "GET_VERSUS_LOBBY_MESSAGES";
export const SET_VERSUS_LOBBY_MESSAGE = "SET_VERSUS_LOBBY_MESSAGE";
export const ERROR_FETCHING_LOBBY_MESSAGES = "ERROR_FETCHING_LOBBY_MESSAGES";
export const POST_VERSUS_LOBBY_MESSAGE = "POST_VERSUS_LOBBY_MESSAGE";
export const POSTED_VERSUS_LOBBY_MESSAGE = "POSTED_VERSUS_LOBBY_MESSAGE";



// Search Game
export const SEARCH_GAME = "SEARCH_GAME";
export const FOUND_GAME = "FOUND_GAME";



// PLAY USER GAME
export const PLAY_UPDATE = "PLAY_UPDATE";
export const PLAY_UPDATED = "PLAY_UPDATED";
export const GET_USER_GAME = "GET_USER_GAME";
export const GOTTEN_USER_GAME = "GOTTEN_USER_GAME";



// Games
export const CREATE_GAME = "CREATE_GAME";
export const CREATED_GAME = 'CREATED_GAME';
export const UPDATE_GAME = 'UPDATE_GAME';
export const UPDATED_GAME = 'UPDATED_GAME';

export const RESET_GAME = 'RESET_GAME';


// Versus Games
export const GET_AVAILABLE_VERSUS_GAMES = "GET_AVAILABLE_VERSUS_GAMES";
export const GOTTEN_AVAILABLE_VERSUS_GAMES = "GOTTEN_AVAILABLE_VERSUS_GAMES";


// Scores
export const GET_TOP_SCORES = 'GET_TOP_SCORES';
export const GOTTEN_TOP_SCORES = 'GOTTEN_TOP_SCORES';

export const SET_PROFILE_GAME = 'SET_PROFILE_GAME';
export const GET_PROFILE_GAME = 'GET_PROFILE_GAME';
export const GOTTEN_PROFILE_GAME = 'GOTTEN_PROFILE_GAME';



// Accuracy
export const ADD_ACCURACY = "ADD_ACCURACY";
export const ADD_SCORE = "ADD_SCORE";
export const ADD_TOTAL_ATTEMPTS = "ADD_TOTAL_ATTEMPTS";